import Navbar from "./Navbar";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../utils/SessionProvider";
import ClientLogic from "./clientlogic";
import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "../public/neue-power-trial-ultra.otf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en" className={myFont.className}>
      <body>
        <SessionProvider session={session}>
          {/* <div className="layout-background"> */}
          <ClientLogic>
            <Navbar />
            {children}
          </ClientLogic>
          {/* </div> */}
        </SessionProvider>
      </body>
    </html>
  );
}
